# Generated by Django 6.1.1 on 2026-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0003_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmessage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
