# Generated by Django 6.1.1 on 2026-09-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0004_consultationmessage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('adm4', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSearchCache',
            fields=[
                ('query', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
