# Generated by Django 6.1.1 on 2026-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0005_weathercache_weathersearchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtikelCache',
            fields=[
                ('query', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
